# Generated by Django 3.2.11 on 2022-01-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.TextField()),
                ('ip', models.GenericIPAddressField()),
                ('description', models.TextField()),
                ('vendor', models.TextField()),
                ('part_number', models.TextField()),
                ('serial_number', models.TextField()),
                ('site', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('username', models.TextField()),
                ('passwd', models.CharField(max_length=30)),
            ],
        ),
    ]
