# Generated by Django 3.2.11 on 2022-01-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netinventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='passwd',
            field=models.CharField(max_length=80),
        ),
    ]
