# Generated by Django 3.2.11 on 2022-01-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netinventory', '0003_alter_nodes_passwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='snmpcommunity',
            field=models.TextField(default='TORONTO.RO.SNMP'),
            preserve_default=False,
        ),
    ]
