# Generated by Django 3.2.11 on 2022-02-01 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('netinventory', '0005_alter_inventory_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Timestamp'),
            preserve_default=False,
        ),
    ]
