# Generated by Django 3.2.11 on 2022-02-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netinventory', '0007_alter_inventory_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('log', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
