# Generated by Django 3.2.11 on 2022-05-02 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netinventory', '0010_rename_changelog_inventorylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorylog',
            old_name='log',
            new_name='name',
        ),
    ]
