# Generated by Django 3.2.11 on 2022-05-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netinventory', '0011_rename_log_inventorylog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='site',
            field=models.TextField(default='Toronto'),
            preserve_default=False,
        ),
    ]
