# Generated by Django 3.2.11 on 2022-05-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netinventory', '0012_inventorylog_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodes',
            options={'ordering': ['ip'], 'verbose_name': 'Nodes', 'verbose_name_plural': 'Nodes'},
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='log_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
